### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by toshibochan** [steve228uk/homebridge-magichome#10]
this plugin is compatible with Eastlion RGB Wi-Fi Strip Controller?

**Comment by toshibochan** [comment]
when i start homebridge say:

Loaded plugin: homebridge-magichome
homebridge API version: 2.1

why say homebridge API version: 2.1?
my homebridge showing 0.4.16.

**Comment by steve228uk** [comment]
@toshibochan You'd need to check with the Homebridge repo re: API version.

That controller should work but I've not personally tested it so can't guarantee it.
