### ISSUE TITLE
Multiple Accessories 

### ISSUE THREAD

**Issue by nulloxide** [steve228uk/homebridge-magichome#13]
I have multiple LED controllers setup , but only the last one in config.json will show up in homebridge . 
here is my config.json file for magic home  : 

"accessories": [{
		"accessory": "MagicHome",
		"name": "LivingRoom Celling Light",
		"ip": "192.168.1.151",
		"setup": "RGBW",
		"purewhite": false
	}],
	"accessories": [{
		"accessory": "MagicHome",
		"name": "Bathroom Celling Light",
		"ip": "192.168.1.150",
		"setup": "RGBW3",
		"purewhite": false
	}],

**Comment by steve228uk** [comment]
Try this…

```
"accessories": [{
"accessory": "MagicHome",
"name": "LivingRoom Celling Light",
"ip": "192.168.1.151",
"setup": "RGBW",
"purewhite": false
}, {
"accessory": "MagicHome",
"name": "Bathroom Celling Light",
"ip": "192.168.1.150",
"setup": "RGBW3",
"purewhite": false
}]
```

**Comment by nulloxide** [comment]
Thanks a lot , works perfectly. 
do MOSFETs on your unit make storage noise too ?

**Comment by steve228uk** [comment]
@nulloxide No problem 😊 I think one of my LED controllers was making a slight hum but nothing I was concerned about. Or is it the Pi that's causing issues?
