### ISSUE TITLE
Saturation not a 100%

### ISSUE THREAD

**Issue by wyteco** [steve228uk/homebridge-magichome#20]
First of all thank you for creating this plugin! It works very well except one thing:

I also have the XSOURCE controller you had in your tutorial. When I change the colour to e.g red the colour is a very light, unsaturated, red. The Command Line in Raspbian says: HUE: 0, SATURATION: 100. If I use the Magic Home App, though, and set the colour to red it becomes red.

I also tried using Siri and asking her to set the colour to red but the same thing happens. 

The preview of the colour wheel in the HomeKit app shows a very well saturated red.

Thank you!

**Comment by Zacknetic** [comment]
I've come across this bug as well. Not exactly sure where it comes from but it eventually sorts itself out.

**Comment by wyteco** [comment]
Here's an image of how "blue" looks like: 
![img_8055](https://user-images.githubusercontent.com/29824653/28679886-e070b80a-72f4-11e7-84d0-b26edad0c43a.jpg) (The image is extremely underexposed, you can see that it is not rgb(0,0,255))

@Lethegrin please tell me more, how long did it take for you to sort out? What are possible reasons for that, e.g have you restarted homebridge a couple of times?

**Comment by gerritfries** [comment]
Got the same issue and I couldn't fix it yet. Got two of the same controllers. One is perfectly working and gives me 100% saturation - the other one only gives me pale colors. It's driving me nuts. But it seems its somehow a hardware issue(?). Though they both work fine with MagicHome.

**Comment by Zacknetic** [comment]
@wytemusic This is a hardware issue.  What is your setup? Can you show me your config.json and a link to your LEDs? Are they RGB or RGBW or RGBWW?

**Comment by wyteco** [comment]
I'm using IKEA's "Ledberg" rgb strips. They have 4 rails: +48V, G, B, R. I cut the wire and inserted them into the "SUNIX 5 Channel RGB Controller" (I have the Sunix version though the XSource one is the same) (here is the link to the [XSource model](https://www.amazon.com/XCSOURCE-Android-Channels-Controller-LD686/dp/B01AA6221S/ref=sr_1_18?ie=UTF8&qid=1501199398&sr=8-18&keywords=rgb+controller) and here to the [Sunix model](https://www.amazon.de/Kontroller-Wireless-LED-Streifen-Fernbedienung-Smartphones/dp/B01J5A7ABW/ref=pd_sbs_107_1?_encoding=UTF8&psc=1&refRID=GNDCXP3AVW62ENBV0ZX5) (this one is from Amazon in Germany since I wasn't able to find the controller in Amazon US)).

The controller has 5 (+1) Outputs: V+, R, G, B, CW, WW.

I'm powering the controller with an 19V DC @ 2,37A powerbrick from an old Acer laptop. 

Here is a [gist of my config](https://gist.github.com/wytemusic/7a57c27f36923d341e3f1de0e7eb7951).

**Comment by wyteco** [comment]
Should I send the controller back to Amazon? How could it be a hardware issue, might it not be "only" a software bug?

**Comment by Zacknetic** [comment]
Okay this is your issue. This plugin does not work with RGBWW controllers. It says it does, but it does not.  Try changing "purewhite" to true.  see if that changes anything. If not post back and I will guide you how to fix the problem.

Secondly, you should make use of those cw and ww channels. They're really cool.  This is what I use. https://www.amazon.com/gp/product/B06XCGKM3Z/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by wyteco** [comment]
Wow that seems to be cool! Didn’t know they exist. 

I have somewhat good news! It actually fixed itself, somehow. Here is what I did (neither are all steps necessary nor might they fix it for you):

I..
1) shut homebridge down
2) shut raspberry pi down
3) turned raspberry pi back on
4) force quit HomeKit app in iOS
5) cd .homebridge
6) rm -rf /persist
7) removed homebridge-bridge in HomeKit app (so with it all accessories)
8) started homebridge again
9) reconfigured homebridge in HomeKit app

After those steps it suddenly worked again!

I think I shouldn’t close this thread at least for now until we know @gerritfries could fix it, too!

Thank you for your help!

**Comment by gerritfries** [comment]
Thank you so far! I'll try fixing it tomorrow as I am participating a wedding right now. I'll let you know if it did work out for me aswell! 

Edit: It's working - Thank you so much!
