### ISSUE TITLE
Last color set from magic home app only color available in homekit

### ISSUE THREAD

**Issue by grimmsq** [steve228uk/homebridge-magichome#21]
Hello, first I would like to thank @steve228uk for this plug in, second, I have this issue maybe someone ran into it before. The only color available (it doesn't matter what color I chose from the homekit app) is the one that was last set in the MagicHome Pro app. All I can do is turn on and of from the apple homekit app, brightness or color change doesn't work. Thanks, in advance!

**Comment by Zacknetic** [comment]
Tell us your controller hardware as well as many wires it uses. Pictures are helpful

**Comment by grimmsq** [comment]
@Lethegrin, thanks, just figured it out, even thou I'm using an RGB led strip needed to set RGBWW in the config.json. I'm using the "5 Channel Controller for RGB LED Strip". Thank you for your help.

**Comment by Zacknetic** [comment]
That's right. No worries. Glad to be of service.
