### ISSUE TITLE
Bulb not responding

### ISSUE THREAD

**Issue by monty77uk** [steve228uk/homebridge-magichome#3]
```
./flux_led.py -s
1 bulbs found
  ACCF2341CBA8 192.168.1.138
```

..I can control using script just fine, but not via Homebridge.  Cannot read bulb state or control it.

JSON entry looks like:

```
 "accessories": [
   {
       "accessory": "MagicHome",
       "name": "test",
       "ip": "192.168.1.138",
       "setup": "RGBW",
       "purewhite": false
   }
]
```

No errors in the log on starting HB

```
[12/10/2016, 8:45:46 PM] [test] Initializing MagicHome accessory...
[12/10/2016, 8:45:46 PM] [test] DEVICE COLOR: 255,100,50
```

..that's not the colour though.

Works fine using bulb's app.

**Comment by steve228uk** [comment]
@monty77uk As per the docs, when using a bulb it will likely need the `purewhite` option set to true. Please try that and reopen if you have further issues.
