### ISSUE TITLE
What IP should I add?

### ISSUE THREAD

**Issue by heisbrot** [steve228uk/homebridge-magichome#41]
Hey,

so I purchased a [LED Wifi Controller.](https://www.ebay.de/itm/Wifi-RGB-RGBW-Led-Kontroller-Controller-Steuerung-f%C3%BCr-Android-IOS-Echo-Alexa/253455765885?ssPageName=STRK%3AMEBIDX%3AIT&var=552628926321&_trksid=p2057872.m2749.l2649) 

I connected it via Magic Home Wifi app. Choose LED02... Wifi name, choose own network and done.
From the app everything is working.

Homebridge is working and connected to the Home App. But I cant figure out what IP I should set in the config.json. Should it be the IP of the device homebridge is running? Or should it be the IP of my wifi network? Or the IP of my router?

Best Regards

**Comment by isignedup** [comment]
IP of the Magic Home device (i.e. the LED strip). The MAC address can be found through the Magic Home app via the gear icon and then device settings. Using the MAC address, look up the IP from the DHCP table on your router (might want to considering assigning the MAC address to a specific IP outside of the DHCP range).

**Comment by heisbrot** [comment]
Thanks! Just got everything working! ;)
