### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by grstreten** [steve228uk/homebridge-magichome#5]
Brightness seems to flit between 100% and 40% fairly randomly as different brightnesses are chosen. 

Config is as follows:
`   {
       "accessory": "MagicHome",
       "name": "Bedside Lamp",
       "ip": "192.168.0.21",
       "setup": "RGBWW",
       "purewhite": true
   },`

Bulb is one of these https://www.amazon.com/MagicLight-WiFi-Smart-Light-Bulb/dp/B00SIDVZSW

Any ideas? Many thanks!

**Comment by grstreten** [comment]
Fixed: changed `setup` to `RGBW` instead with `purewhite` set to `true` instead

**Comment by jimbo-83** [comment]
Hey, I'm having a similar issue with these bulbs. Works great but not very bright. Any suggestions?
